### ISSUE TITLE
Harbour and marina names not rendered

### ISSUE THREAD

**Issue by Krillle** [OpenSeaMap/online_chart#106]
Names of harbours and marinas are not rendered in OpenSeaMap any more. The Marina symbol is overlaying the OpenStreetMap tiles in a way that the names rendered there are not readable at all.

Example: http://map.openseamap.org/?zoom=18&lat=39.55557&lon=2.62547&layers=BFTFFFFFFTF0TFFFFFFFFF

**Comment by wschildbach** [comment]
You can switch off the Sea Marks layer using the "View" menu, to see the names again.
I am not sure how we would really fix this issue properly since the text and the Sea Mark reside in different layers; and the Sea Mark layer can be switched on and off.

**Comment by wschildbach** [comment]
I don't see how we can easily fix this, and we have a workaround, so I propose we close this as wontfix.

**Comment by Krillle** [comment]
I don't agree to the proposal. Marina names have been rendered in the past. Example here: https://bit.ly/2zbT3qR (I assume its got lost switching to Java rendering engine.)

Besides harbour icons are not necessarily placed on the same nodes as the "street" marina tags.

Marina names are essential and would be very helpful. Especially in apps and maps without the option to switch off seaman layer.

**Comment by wschildbach** [comment]
Ok, it seems this is two issues in one:
1) the seamark layer used to contain marina names, but does not anymore. @malcolmh, is this correct and would you consider fixing this?
2) the OSM layer also contains these names and so they sometimes overlap, sometimes appear twice. Now that we also control the rendering of the osm layer, we could consider removing marina names in the osm layer.

**Comment by malcolmh** [comment]
Fixed

**Comment by wschildbach** [comment]
It seems the original issue is not fixed yet. With the link above, club del Mar ist obscored by the seamark layer.
@malcolmh Should the seamark layer also render the marina name?

**Comment by Krillle** [comment]
I think it it fixed, but needs some time until the whole world is re-rendered. 

Check here for already new rendered Seamap tiles: http://map.openseamap.org/?zoom=16&lat=52.42679&lon=13.64169&layers=BFTFFFFFFTF0TFFFFFFFFF

**Comment by malcolmh** [comment]
Yes, the seamark layer does do on-demand rendering. It is only updated when a seamark is edited. The renderer then re-renders a 3x3 zoom-12 tile area around the changed object(s). I have touched the marina in question, so the new rendering should appear in the next hour.

**Comment by wschildbach** [comment]
Thanks Malcolm, then it appears we can fix this one. Removing marina names from the osm layer can become a seperate issue.
